/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.logindoprojetointegrador;

import javax.swing.JOptionPane;
import javax.swing.JButton;
import javax.swing.JFrame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/**
 *
 * @author gabriel
 */
public class CadastroFrame extends javax.swing.JFrame {

    /**
     * Creates new form CadastroFrame
     */
    public CadastroFrame() {
        initComponents();
        setLocationRelativeTo(null); //para deixar a tela no meio creio que seja melhor
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeCadastroField = new javax.swing.JTextField();
        emailCadastroField = new javax.swing.JTextField();
        passwordCadastroField = new javax.swing.JPasswordField();
        registrarJButton = new javax.swing.JButton();
        voltarLoginButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomeCadastroField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeCadastroFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nomeCadastroField, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 300, 410, 90));
        getContentPane().add(emailCadastroField, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 420, 410, 80));
        getContentPane().add(passwordCadastroField, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 540, 410, 80));

        registrarJButton.setContentAreaFilled(false);
        registrarJButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(registrarJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 660, 260, 60));

        voltarLoginButton.setContentAreaFilled(false);
        voltarLoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltarLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarLoginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(voltarLoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 140, 260, 20));

        jButton3.setBackground(new java.awt.Color(204, 153, 255));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Play");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 30));

        jButton4.setBackground(new java.awt.Color(204, 153, 255));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Pause");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 70, 30));

        jButton5.setBackground(new java.awt.Color(204, 153, 255));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Resume");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 80, 30));

        jButton6.setBackground(new java.awt.Color(204, 153, 255));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("+");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 40, 30));

        jButton7.setBackground(new java.awt.Color(204, 153, 255));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("-");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 40, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeCadastroFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeCadastroFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeCadastroFieldActionPerformed

    private void voltarLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarLoginButtonActionPerformed
        LoginFrame voltaFrame = new LoginFrame();
        voltaFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarLoginButtonActionPerformed

    private void registrarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarJButtonActionPerformed
        String nome = nomeCadastroField.getText(); 
        String email = emailCadastroField.getText();
        String senha = new String(passwordCadastroField.getPassword()); 
        
        
        if(nome.length() == 0 && email.length() == 0 &&  senha.length() == 0){ 
            JOptionPane.showMessageDialog (null, "Insira seus dados!");
          
        }
        else if(email.length() == 0 ){ //verifica se o email está vazio
            JOptionPane.showMessageDialog (null, "Preencha o seu email!");
          
        }
        else if( senha.length() == 0 ){ //verifica se a senha está vazio
            JOptionPane.showMessageDialog (null, "Preencha a sua senha!");
          
        }
        else if( nome.length() == 0){ //verifica se o nome está vazio
            JOptionPane.showMessageDialog (null, "Preencha seu nome!");
        }
        else{
            try{
                Usuario usuario = new Usuario(nome,email,senha);
                DAO dao = new DAO();
                    
                if(dao.existe(usuario)){
                JOptionPane.showMessageDialog (null, "Cadastro já existente! Faça o login");
                
               
            }
            else{
   
            int escolha = JOptionPane.showConfirmDialog(null, "Confirmar cadastro?","Confirme o cadastro",JOptionPane.OK_CANCEL_OPTION);
            if(escolha == JOptionPane.OK_OPTION){
            dao.inserirCadastro(usuario);
            JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso");
                        
            nomeCadastroField.setText("");
            emailCadastroField.setText("");
            passwordCadastroField.setText(""); 
                        
                         
                    }
                }
            }
            catch(Exception e){
             JOptionPane.showMessageDialog(null, "Falha técnica, tente mais tarde");
             e.printStackTrace(); 
             }
        } 
    }//GEN-LAST:event_registrarJButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // play music
        
        MusicPlayer.playMusic("/gameMusic.wav");
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // aumentar volume
        MusicPlayer.increaseVolume();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // pausar musica
        MusicPlayer.pauseMusic();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // resume musica
        MusicPlayer.resumeMusic();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // diminuir volume
        MusicPlayer.decreaseVolume();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailCadastroField;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nomeCadastroField;
    private javax.swing.JPasswordField passwordCadastroField;
    private javax.swing.JButton registrarJButton;
    private javax.swing.JButton voltarLoginButton;
    // End of variables declaration//GEN-END:variables
}
