/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.logindoprojetointegrador;

import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class telaGerenciarPerguntas extends javax.swing.JFrame {
    private javax.swing.ButtonGroup buttonGroup;
    private int valorSelecionado;
    private Usuario usuario;
    /**
     * Creates new form telaGerenciarPerguntas
     */
    public telaGerenciarPerguntas(Usuario usuario) {
        initComponents();
        buscarOrgaos(); 
        configurarButtonGroup();
        this.usuario = usuario; 
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoEnunciado = new javax.swing.JTextField();
        campoAlternativaA = new javax.swing.JTextField();
        campoAlternativaC = new javax.swing.JTextField();
        campoAlternativaD = new javax.swing.JTextField();
        campoAlternativaB = new javax.swing.JTextField();
        botaoAdicionar = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();
        orgaos = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        questaoDButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoEnunciado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEnunciadoActionPerformed(evt);
            }
        });
        getContentPane().add(campoEnunciado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 640, 100));
        getContentPane().add(campoAlternativaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 640, 100));
        getContentPane().add(campoAlternativaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 640, 100));

        campoAlternativaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoAlternativaDActionPerformed(evt);
            }
        });
        getContentPane().add(campoAlternativaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, 640, 100));
        getContentPane().add(campoAlternativaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 640, 100));

        botaoAdicionar.setContentAreaFilled(false);
        botaoAdicionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 320, 170, 120));

        botaoVoltar.setContentAreaFilled(false);
        botaoVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 180, 170, 130));

        orgaos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgaosActionPerformed(evt);
            }
        });
        getContentPane().add(orgaos, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 40, -1, -1));

        jRadioButton1.setText("A");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 170, -1, -1));

        jRadioButton2.setText("B");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 290, -1, -1));

        jRadioButton3.setText("C");
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 440, -1, -1));

        questaoDButton.setText("D");
        questaoDButton.setAlignmentX(1.0F);
        questaoDButton.setContentAreaFilled(false);
        getContentPane().add(questaoDButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 570, 40, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Gerencia Pergunta.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoEnunciadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEnunciadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEnunciadoActionPerformed

    private void orgaosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgaosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orgaosActionPerformed

    private void botaoAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarActionPerformed
        String enunciado =  campoEnunciado.getText(); 
        String alternativaA = campoAlternativaA.getText();
        String alternativaB = campoAlternativaB.getText();
        String alternativaC = campoAlternativaC.getText();
        String alternativaD = campoAlternativaD.getText();
        int id_orgao = orgaos.getSelectedIndex(); 
        int valorSelecionado1 = valorSelecionado;
        int id_professor = usuario.pegarIDProfessor(); 
        if(enunciado  == null|| enunciado.length() == 0 || alternativaA == null || alternativaA.length() == 0 || alternativaB == null || alternativaB.length() == 0 || alternativaC == null || alternativaC.length() == 0 || alternativaD == null || alternativaD.length() == 0 || valorSelecionado1 == 0){
            JOptionPane.showMessageDialog (null, "Preencha a pergunta por completo!");
          
        }
        else{
            try{
                int escolha = JOptionPane.showConfirmDialog(null, "Adicionar nova pergunta?","Confirme a nova pergunta",JOptionPane.OK_CANCEL_OPTION);
                    if(escolha == JOptionPane.OK_OPTION){
                        construtorPergunta  pergunta = new construtorPergunta(enunciado,id_professor,alternativaA,alternativaB,alternativaC,alternativaD,id_orgao,valorSelecionado1);
                        DAO dao = new DAO();
                        dao.inserirPergunta(pergunta,usuario);
                        JOptionPane.showMessageDialog(null, "Pergunta cadastrado com sucesso");
                        
                        campoEnunciado.setText("");
                        campoAlternativaA.setText("");
                        campoAlternativaB.setText("");
                        campoAlternativaC.setText("");
                        campoAlternativaD.setText("");
                        buscarOrgaos();  
                    }
            }
             catch(Exception e){
                 JOptionPane.showMessageDialog(null, "Falha técnica, tente mais tarde");
                e.printStackTrace(); 
             }
        } 
    }//GEN-LAST:event_botaoAdicionarActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
      
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        TelaProfessor tl = new TelaProfessor(usuario);
        tl.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void campoAlternativaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoAlternativaDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoAlternativaDActionPerformed
    
    private void buscarOrgaos(){
        try{
        DAO dao = new DAO();
        construtorPergunta[] perguntas = dao.obterOrgaos();
        
        // Convertendo o array de construtorPergunta para um array de String
        String[] nomes = new String[perguntas.length];
        for (int i = 0; i < perguntas.length; i++) {
            nomes[i] = perguntas[i].toString();
        }
        
        orgaos.setModel(new DefaultComboBoxModel<>(nomes));
    }
    catch (Exception e){
        JOptionPane.showMessageDialog(null, "Cursos indisponíveis, tente novamente mais tarde.");
        e.printStackTrace();
    }
    }
      private void configurarButtonGroup() {
        buttonGroup = new javax.swing.ButtonGroup();
        buttonGroup.add(jRadioButton1);
        buttonGroup.add(jRadioButton2);
        buttonGroup.add(jRadioButton3);
        buttonGroup.add(questaoDButton);

        // Definir ActionCommands
        jRadioButton1.setActionCommand("1");
        jRadioButton2.setActionCommand("2");
        jRadioButton3.setActionCommand("3");
        questaoDButton.setActionCommand("4");

        // Adicionar ActionListeners
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonActionPerformed(evt);
            }
        });
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonActionPerformed(evt);
            }
        });
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonActionPerformed(evt);
            }
        });
        questaoDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonActionPerformed(evt);
            }
        });
    }

    private void jRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Obter o ActionCommand e converter para inteiro
        String actionCommand = ((javax.swing.JRadioButton) evt.getSource()).getActionCommand();
        valorSelecionado = Integer.parseInt(actionCommand);

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaGerenciarPerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaGerenciarPerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaGerenciarPerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaGerenciarPerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(Usuario usuario) {
                new telaGerenciarPerguntas(usuario).setVisible(true);
            }

            @Override
            public void run() {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        });
    }
      
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdicionar;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JTextField campoAlternativaA;
    private javax.swing.JTextField campoAlternativaB;
    private javax.swing.JTextField campoAlternativaC;
    private javax.swing.JTextField campoAlternativaD;
    private javax.swing.JTextField campoEnunciado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JComboBox<String> orgaos;
    private javax.swing.JRadioButton questaoDButton;
    // End of variables declaration//GEN-END:variables
}
