/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.logindoprojetointegrador;

import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class telaGerenciarPerguntas extends javax.swing.JFrame {
    private javax.swing.ButtonGroup buttonGroup;
    private int valorSelecionado;
    private Usuario usuario;
    /**
     * Creates new form telaGerenciarPerguntas
     */
    public telaGerenciarPerguntas(Usuario usuario) {
        initComponents();
        buscarOrgaos(); 
        configurarButtonGroup();
        this.usuario = usuario; 
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoEnunciado = new javax.swing.JTextField();
        campoAlternativaA = new javax.swing.JTextField();
        campoAlternativaC = new javax.swing.JTextField();
        campoAlternativaD = new javax.swing.JTextField();
        campoAlternativaB = new javax.swing.JTextField();
        botaoAdicionar = new javax.swing.JButton();
        botaoRemover = new javax.swing.JButton();
        orgaos = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        campoEnunciado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEnunciadoActionPerformed(evt);
            }
        });

        campoAlternativaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoAlternativaDActionPerformed(evt);
            }
        });

        botaoAdicionar.setText("Adcionar");
        botaoAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarActionPerformed(evt);
            }
        });

        botaoRemover.setText("Voltar");
        botaoRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverActionPerformed(evt);
            }
        });

        orgaos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgaosActionPerformed(evt);
            }
        });

        jRadioButton1.setText("A");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("B");

        jRadioButton3.setText("C");

        jRadioButton4.setText("D");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(botaoAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addComponent(botaoRemover)
                        .addGap(90, 90, 90))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(campoEnunciado)
                                .addGap(69, 69, 69)
                                .addComponent(orgaos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(campoAlternativaA)
                                    .addComponent(campoAlternativaD, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                    .addComponent(campoAlternativaC)
                                    .addComponent(campoAlternativaB))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRadioButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRadioButton4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRadioButton1, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(orgaos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoEnunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campoAlternativaA, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoAlternativaB, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campoAlternativaC, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoAlternativaD, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoAdicionar)
                            .addComponent(botaoRemover)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton4)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoEnunciadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEnunciadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEnunciadoActionPerformed

    private void orgaosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgaosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orgaosActionPerformed

    private void botaoAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarActionPerformed
        String enunciado =  campoEnunciado.getText(); 
        String alternativaA = campoAlternativaA.getText();
        String alternativaB = campoAlternativaB.getText();
        String alternativaC = campoAlternativaC.getText();
        String alternativaD = campoAlternativaD.getText();
        int id_orgao = orgaos.getSelectedIndex(); 
        int valorSelecionado1 = valorSelecionado;
        int id_professor = usuario.pegarIDProfessor(); 
        if(enunciado  == null|| enunciado.length() == 0 || alternativaA == null || alternativaA.length() == 0 || alternativaB == null || alternativaB.length() == 0 || alternativaC == null || alternativaC.length() == 0 || alternativaD == null || alternativaD.length() == 0 || valorSelecionado1 == 0){
            JOptionPane.showMessageDialog (null, "Preencha a pergunta por completo!");
          
        }
        else{
            try{
                int escolha = JOptionPane.showConfirmDialog(null, "Adicionar nova pergunta?","Confirme a nova pergunta",JOptionPane.OK_CANCEL_OPTION);
                    if(escolha == JOptionPane.OK_OPTION){
                        construtorPergunta  pergunta = new construtorPergunta(enunciado,id_professor,alternativaA,alternativaB,alternativaC,alternativaD,id_orgao,valorSelecionado1);
                        DAO dao = new DAO();
                        dao.inserirPergunta(pergunta,usuario);
                        JOptionPane.showMessageDialog(null, "Pergunta cadastrado com sucesso");
                        
                        campoEnunciado.setText("");
                        campoAlternativaA.setText("");
                        campoAlternativaB.setText("");
                        campoAlternativaC.setText("");
                        campoAlternativaD.setText("");
                        buscarOrgaos();  
                    }
            }
             catch(Exception e){
                 JOptionPane.showMessageDialog(null, "Falha técnica, tente mais tarde");
                e.printStackTrace(); 
             }
        } 
    }//GEN-LAST:event_botaoAdicionarActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
      
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void botaoRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverActionPerformed
        TelaProfessor tl = new TelaProfessor(usuario);
        tl.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_botaoRemoverActionPerformed

    private void campoAlternativaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoAlternativaDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoAlternativaDActionPerformed
    
    private void buscarOrgaos(){
        try{
        DAO dao = new DAO();
        construtorPergunta[] perguntas = dao.obterOrgaos();
        
        // Convertendo o array de construtorPergunta para um array de String
        String[] nomes = new String[perguntas.length];
        for (int i = 0; i < perguntas.length; i++) {
            nomes[i] = perguntas[i].toString();
        }
        
        orgaos.setModel(new DefaultComboBoxModel<>(nomes));
    }
    catch (Exception e){
        JOptionPane.showMessageDialog(null, "Cursos indisponíveis, tente novamente mais tarde.");
        e.printStackTrace();
    }
    }
      private void configurarButtonGroup() {
        buttonGroup = new javax.swing.ButtonGroup();
        buttonGroup.add(jRadioButton1);
        buttonGroup.add(jRadioButton2);
        buttonGroup.add(jRadioButton3);
        buttonGroup.add(jRadioButton4);

        // Definir ActionCommands
        jRadioButton1.setActionCommand("1");
        jRadioButton2.setActionCommand("2");
        jRadioButton3.setActionCommand("3");
        jRadioButton4.setActionCommand("4");

        // Adicionar ActionListeners
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonActionPerformed(evt);
            }
        });
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonActionPerformed(evt);
            }
        });
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonActionPerformed(evt);
            }
        });
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonActionPerformed(evt);
            }
        });
    }

    private void jRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Obter o ActionCommand e converter para inteiro
        String actionCommand = ((javax.swing.JRadioButton) evt.getSource()).getActionCommand();
        valorSelecionado = Integer.parseInt(actionCommand);

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaGerenciarPerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaGerenciarPerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaGerenciarPerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaGerenciarPerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(Usuario usuario) {
                new telaGerenciarPerguntas(usuario).setVisible(true);
            }

            @Override
            public void run() {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        });
    }
      
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdicionar;
    private javax.swing.JButton botaoRemover;
    private javax.swing.JTextField campoAlternativaA;
    private javax.swing.JTextField campoAlternativaB;
    private javax.swing.JTextField campoAlternativaC;
    private javax.swing.JTextField campoAlternativaD;
    private javax.swing.JTextField campoEnunciado;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JComboBox<String> orgaos;
    // End of variables declaration//GEN-END:variables
}
