/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.logindoprojetointegrador;

import java.awt.Font;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gabriel
 */
public class TelaRanking extends javax.swing.JFrame {
    int contador = 0;
    int id_aluno;
    private Usuario usuario; 

    /**
     * Creates new form TelaRanking
     */
    public TelaRanking(int id_aluno, int contador, Usuario usuario) throws Exception {
        this.contador = contador;
        this.id_aluno = id_aluno;
        this.usuario = usuario; 
        initComponents();
        jLabel3.setText(Integer.toString(contador)); 
        setLocationRelativeTo(null);
        
        DAO dao = new DAO(); 
 // Desativei para não lotar o bd nos testes mas está funcionando
        try{
             dao.inserirRanking(contador,id_aluno);
        }
        catch(Exception e){
           JOptionPane.showMessageDialog (null, "Problemas técnicos. Tente novamente mais tarde");
            e.printStackTrace();
        }
        
        // construir os if's e definir as labels
        List<Integer> top5Pontuacoes = dao.verificaTOP5(); 
        List<String> top5Nomes = dao.verificaNOMETOP5();

        nome1Label.setText("");
        pontuacao1Label.setText("");

        nome2Label.setText("");
        pontuacao2Label.setText("");

        nome3Label.setText("");
        pontuacao3Label.setText("");

        nome4Label.setText("");
        pontuacao4Label.setText("");

        nome5Label.setText("");
        pontuacao5Label.setText("");

        // Atualize os rótulos apenas se os valores existirem
        if (top5Nomes.size() > 0) {
                nome1Label.setText(top5Nomes.get(0));
            if (top5Pontuacoes.size() > 0) {
                pontuacao1Label.setText(Integer.toString(top5Pontuacoes.get(0)));
            }
        }

        if (top5Nomes.size() > 1) {
            nome2Label.setText(top5Nomes.get(1));
            if (top5Pontuacoes.size() > 1) {
                pontuacao2Label.setText(Integer.toString(top5Pontuacoes.get(1)));
            }
        }

        if (top5Nomes.size() > 2) {
            nome3Label.setText(top5Nomes.get(2));
            if (top5Pontuacoes.size() > 2) {
                pontuacao3Label.setText(Integer.toString(top5Pontuacoes.get(2)));
            }
        }

        if (top5Nomes.size() > 3) {
            nome4Label.setText(top5Nomes.get(3));
            if (top5Pontuacoes.size() > 3) {
                pontuacao4Label.setText(Integer.toString(top5Pontuacoes.get(3)));
            }
        }

        if (top5Nomes.size() > 4) {
            nome5Label.setText(top5Nomes.get(4));
            if (top5Pontuacoes.size() > 4) {
                pontuacao5Label.setText(Integer.toString(top5Pontuacoes.get(4)));
            }
        }
    }

            

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nome1Label = new javax.swing.JLabel();
        pontuacao1Label = new javax.swing.JLabel();
        nome2Label = new javax.swing.JLabel();
        pontuacao2Label = new javax.swing.JLabel();
        pontuacao5Label = new javax.swing.JLabel();
        nome5Label = new javax.swing.JLabel();
        pontuacao4Label = new javax.swing.JLabel();
        nome4Label = new javax.swing.JLabel();
        pontuacao3Label = new javax.swing.JLabel();
        nome3Label = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nome1Label.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(nome1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 160, 50));
        nome1Label.setFont(new Font("Arial", Font.PLAIN, 18));
        getContentPane().add(pontuacao1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 130, 60));
        pontuacao1Label.setFont(new Font("Arial", Font.PLAIN, 18));

        nome2Label.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(nome2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 160, 50));
        nome2Label.setFont(new Font("Arial", Font.PLAIN, 18));
        getContentPane().add(pontuacao2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, 130, 60));
        pontuacao2Label.setFont(new Font("Arial", Font.PLAIN, 18));
        getContentPane().add(pontuacao5Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 590, 130, 60));
        pontuacao5Label.setFont(new Font("Arial", Font.PLAIN, 18));
        getContentPane().add(nome5Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 590, 160, 50));
        nome5Label.setFont(new Font("Arial", Font.PLAIN, 18));
        getContentPane().add(pontuacao4Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 490, 130, 60));
        pontuacao4Label.setFont(new Font("Arial", Font.PLAIN, 18));
        getContentPane().add(nome4Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 160, 50));
        nome4Label.setFont(new Font("Arial", Font.PLAIN, 18));
        getContentPane().add(pontuacao3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 130, 60));
        pontuacao3Label.setFont(new Font("Arial", Font.PLAIN, 18));
        getContentPane().add(nome3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 160, 50));
        nome3Label.setFont(new Font("Arial", Font.PLAIN, 18));

        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/red play.png"))); // NOI18N
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/red pause.png"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 40, 40));

        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/red diminuir.png"))); // NOI18N
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 40, 40));

        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/red aumentar.png"))); // NOI18N
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 40, 40));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botaosair - Copia.png"))); // NOI18N
        jButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 110, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/voltarbutton.png"))); // NOI18N
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 6, true));
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 630, 130, 50));

        jLabel2.setText("SUA PONTUAÇÃO:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 290, 30));
        jLabel2.setFont(new Font("Arial", Font.PLAIN, 18));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 90, 80));
        jLabel3.setFont(new Font("Arial", Font.PLAIN, 18));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Design sem nome (3).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // play music

        MusicPlayer.playMusic("/gameMusic.wav");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // pausar musica
        MusicPlayer.pauseMusic();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // diminuir volume
        MusicPlayer.decreaseVolume();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // aumentar volume
        MusicPlayer.increaseVolume();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        int escolha = JOptionPane.showConfirmDialog(null, "Deseja sair e voltar para a tela de login?","Sair!",JOptionPane.OK_CANCEL_OPTION);
        if(escolha == JOptionPane.OK_OPTION){
            LoginFrame lf = new LoginFrame();
            lf.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int escolha = JOptionPane.showConfirmDialog(null, "Deseja sair e voltar para a tela inicial?","Sair!",JOptionPane.OK_CANCEL_OPTION);
        if(escolha == JOptionPane.OK_OPTION){
        telaTeste tl = null;
        try {
            tl = new telaTeste(usuario);
        } catch (Exception ex) {
            Logger.getLogger(TelaRanking.class.getName()).log(Level.SEVERE, null, ex);
        }
        tl.setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRanking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRanking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRanking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRanking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(Usuario usuario) throws Exception {
                new TelaRanking(0, 0,usuario).setVisible(true);
            }

            @Override
            public void run() {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        });
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel nome1Label;
    private javax.swing.JLabel nome2Label;
    private javax.swing.JLabel nome3Label;
    private javax.swing.JLabel nome4Label;
    private javax.swing.JLabel nome5Label;
    private javax.swing.JLabel pontuacao1Label;
    private javax.swing.JLabel pontuacao2Label;
    private javax.swing.JLabel pontuacao3Label;
    private javax.swing.JLabel pontuacao4Label;
    private javax.swing.JLabel pontuacao5Label;
    // End of variables declaration//GEN-END:variables
}


// recebe todos os atributos (id_aluno, contador)
//dar um select no banco de dados na tabela alunos: select nome from aluno where id_aluno = ?
// insert into ranking (id_aluno, pontuacao) values (?,?)
// 1 - id_aluno
// 2 - contador
// 2 labels, label.setText(nomeDoAluno), label.setText(contador);
